config/routes.rb
Sawit::Application.routes.draw do

  get "events/index"
  get "pages/ads"
  get "pages/privacy"
  get "pages/sitemap"
   devise_for :users
 

  resources :groups do
    member do
      get :follow
    end
  end

  resources :users do
    member do
      get :following
    end
  end

  resources :pages
  resources :users
  resources :ads

   resources :relationships, only: [:create, :destroy]
  

  resources :jobs do
    resources :comments
    resources :votes
  end

  resources :comments do
    resources :comments
    resources :votes
  end

  

  root :to => "countries#show", :id => '1'

  resources :states   do
    resources :links
    resources :groups do
    resources :links
  end
    resources :jobs 
    resources :resources
    resources :events
    resources :bills
  end

  resources :countries do
    resources :links
    resources :groups do
    resources :links
  end
    resources :jobs 
    resources :resources
    resources :events
    resources :bills
  end

  resources :reps do
    resources :links
  end

resources :districts do
  resources :links
end

resources :resources

resources :groups do
  resources :links
end

resources :cities do
  resources :links do
  resources :comments
  end
  resources :groups do
    resources :links
  end
  resources :jobs
  resources :districts do
    resources :links
  end 
  resources :resources
  resources :events
  resources :ads
  resources :bills
end

resources :links do
    resources :comments
    resources :votes
  end

  resources :events do
    resources :comments
    resources :votes
  end
  
    resources :bills do
    resources :comments
    resources :votes
  end

  

 

end

app/models/state.rb
class State < ActiveRecord::Base
 OUR_EPOCH = Time.local(2005, 12, 8, 7, 46, 43).to_time
	has_many :links
  has_many :groups
  has_many :jobs
  has_many :resources
  has_many :events
  has_many :ads
  has_many :bills
  

	  def score
    ups = votes.where(:up => true).count
    downs = votes.where(:up => false).count
    ups - downs
  end
  

  def hot
  s = score
    displacement = Math.log( [s.abs, 1].max,  10 )
 
    sign = if s > 0
      1
    elsif s < 0
      -1
    else
      0
    end
 
    return (displacement * sign.to_f) + ( (created_at.to_i - OUR_EPOCH.to_i).to_f / 45000 )
  end 
	
end

app/controllers/states_controller.rb
require 'will_paginate/array'
class StatesController < ApplicationController
  before_filter :find_parent, only: [:new, :create]
  http_basic_authenticate_with name: "sammy1088", password: "Ce66$rio", except: [:show]
  
  def slug
    name.downcase.gsub(" ", "-")  
  end

  def to_param
    "#{id}-#{slug}"
  end

  
  def index
    @states = State.all
    @links = Link.all

  end
  def new
    @state = State.new
    ##@link = @parent.links.new(link_params)
  end
  def create
   ##@link = @parent.links.new(link_params)
    @state = State.new(state_params)
    @state.save
    redirect_to @state
  end
  def destroy
    @state = State.find(params[:id])
    @state.destroy
  end

  def show
    @state = State.find(params[:id])
 @link = Link.find(params[:id])
    @comments = @link.comments

    ##n@district = District.find(params[:id])
    
   
  
    @links = @state.links
    @groups = @state.groups
    @resources = @state.resources
    @ads = @state.ads
    @jobs = @state.jobs.limit(5)
    @events = @state.events.where(['date >= ?', DateTime.now.to_date]).limit(5)
    @bills = @state.bills.where(['date >= ?', DateTime.now.to_date]).limit(2)
    
    
    if params[:sort_by] == "new"
      puts "sort queries called"
      
      @links = @links.order(created_at: :desc)

    else
    
    @links = @links.sort_by{ |l| l.hot }.reverse
    
    
    end

    @links = @links.paginate(:page => params[:page], :per_page => 15)
      respond_to do |format|
    format.html               # /app/views/articles/index.html.erb
    format.html.tablet     # /app/views/posts/index.html+tablet.erb
    end

  end
  private
  def state_params
    params.require(:state).permit(:title, :slug)
  end
  def find_parent
    if params[:state_id]
      @parent = State.find(params[:state_id])
  end
end
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/states/_comments.html.erb
<% link.comments.sort_by{ |c| c.score }.reverse.each do |comment| %>

   <ul> 
     
     
<div class='message_group'>

   <div class="row">
     <% if current_user && current_user.votes.where(:votable_id => comment.id, :up => true).present? %>
                          <div class="ctriggerPL">
                          <span class="glyphicon glyphicon-chevron-up"></span>
                         </div>
                            <% else %>
     <div class="ctrigger">
     <%= link_to comment_votes_path(comment, :vote => {:up => true}), :remote => true, :method => :post, class: "btn btn-small" do %>
      <span class="glyphicon glyphicon-chevron-up"></span>
       <% end %>
       </div>
     <% end %>
     <b><%= comment.user.username %></b>
  <%= comment.score %> points 
          </div> 
     <div class="row">
       <% if current_user && current_user.votes.where(:votable_id => comment.id, :up => false).present? %>
                               <div class="ctriggerPLE">
                                  <span class="glyphicon glyphicon-chevron-down"></span>
                                </div>  
                            <% else %>
       <div class="ctrigger-">
       <%= link_to comment_votes_path(comment, :vote => {:up => false}), :remote => true, :method => :post, class: "btn btn-small" do %>
        <span class="glyphicon glyphicon-chevron-down"></span>
        <% end %>
         </div>
       <% end %>
       <%= auto_link(comment.message, :all, :target => "_blank").html_safe %>
      </div>
                        
     
    
                        <%= link_to "Reply", '#', class: 'reply-link', id: 'reply-link' %>
                  <div class="reply-container", id='reply-container'>
                  <%= form_for(Comment.new, url: comment_comments_path(comment), :remote => true) do |f| %> 
              
                  <%= f.text_area :message, :class => "form-control", :placeholder =>"Add a comment" %>
                    <div class="actions">
                      <%= f.submit :class => "btn btn-primary" %>
              </div>
                  <% end %>
                                               
     </div>
                  
      
<div id="commentcomment">
<%= render partial: "commentscomments", locals: { comments: comment.comments } %>
</div>
</ul>

<% end %>

app/views/states/_commentsL.html.erb
<% bill.comments.sort_by{ |c| c.score }.reverse.each do |comment| %>

   <ul> 
     
     
<div class='message_group'>
   <div class="row">
          <% if current_user && current_user.votes.where(:votable_id => comment.id, :up => true).present? %>
                          <div class="ctriggerPL">
                          <span class="glyphicon glyphicon-chevron-up"></span>
                         </div>
                            <% else %>
     <div class="ctrigger">
      <%= link_to comment_votes_path(comment, :vote => {:up => true}), :remote => true, :method => :post, class: "btn btn-small" do %>
      <span class="glyphicon glyphicon-chevron-up"></span>
       <% end %>
       </div>
     <% end %>
       <%= comment.user.username %>
  <b><%= comment.score %></b> points 
          </div> 
     <div class="row">
       <% if current_user && current_user.votes.where(:votable_id => comment.id, :up => false).present? %>
                               <div class="ctriggerPLE">
                                  <span class="glyphicon glyphicon-chevron-down"></span>
                                </div>  
                            <% else %>
       <div class="ctrigger-">
       <%= link_to comment_votes_path(comment, :vote => {:up => false}), :remote => true, :method => :post, class: "btn btn-small" do %>
        <span class="glyphicon glyphicon-chevron-down"></span>
        <% end %>
         </div>
       <% end %>
       <b><%= auto_link(comment.message, :all, :target => "_blank").html_safe %></b>
      
                        
       </div>
    
                        <%= link_to "Reply", '#', class: 'reply-link', id: 'reply-link' %>
                  <div class="reply-container", id='reply-container'>
                    <%= form_for(Comment.new, url: comment_comments_path(comment), :remote => true) do |f| %> 
              
                  <%= f.text_area :message, :class => "form-control", :placeholder =>"Add a comment" %>
                   <div class="actions">
                      <%= f.submit :class => "btn btn-primary" %>
                 </div>              
                  <% end %>
                                               
     </div>
                  
      
<div id="commentcomment">
<%= render partial: "commentscommentsL", locals: { comments: comment.comments } %>
</div>
</ul>

<% end %>
     
     <div id="commpadB"></div>

app/views/states/index.html.erb
<% @states.each do |state| %>
<p>
	 <%= link_to state.title, state %>
	 <%= link_to 'Destroy', state_path(state),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
	</p>

	 <% end %>

app/views/states/new.html.erb
<%= form_for :state, url: states_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/states/show.html+tablet.erb
<!DOCTYPE html>

<head>
  <title>Democratize! <%= @state.title %> News, Politics, Discussion, Events</title>
  
   <%= stylesheet_link_tag    "mob/mob", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Democratize! <%= @state.title %> is a site for user-generated local news, politics, and opinion sharing in <%= @state.title %>.">
  <meta property="og:image" content='http://i59.tinypic.com/2e4ew5d.jpg'/>
</head>

<div class="bodymob">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
<div class="btn-group">
<button type="button" class="btn btn-default btn-lg navbar-btn navbar-left dropdown-toggle" data-toggle="dropdown">
    Menu <span class="caret"></span>
  </button>
  <ul class="dropdown-menu scrollable-menu" role="menu">
    <li><% if current_user.present? %>
                
                  <%= current_user.username %>
                  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>

                <% else %>
                
                  <li><%= link_to 'Sign In', new_user_session_path %></li>
                  <li><%= link_to 'Register Now!', new_user_registration_path %></li>
                
                <% end %></li>
    <li class="divider"></li>
  
  <li><%= @state.title %> Groups</li>
    <% @groups.each do |group| %>
  <li><%= link_to group.title, [@state, group] %></li>
    <% end %>
  <li><%= @state.title %> News Sources</li>
    <% @resources.each do |resource| %>
    <li><%= link_to resource.title, "http://#{resource.url}", target: '_blank' %></li>
    <% end %>
    
    <li class="divider"></li>
  <li><%= link_to "State Jobs", state_jobs_path(@state) %></li>
  <li><%= link_to "State Events", state_events_path(@state) %></li>
  </ul>
</div>


    <p class="navbar-text"><i class="fa fa-bullhorn"></i> <%= link_to "Democratize!", root_path %></p>

      
  </div>    
  </nav>
  
  
  <center>
    <div id="navtitle">
      <%= @state.title %> News and Politics
    </div>
  <div class="btn-group">
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                          Change Location
                        <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><b><%= link_to "United States", "/" %></a></b></li>
                            <li class="divider"></li>
                          <li><b><%= link_to "Oklahoma", "/states/2-oklahoma" %></a></b></li>
                          <li><%= link_to "Oklahoma City", "/cities/2-oklahomacity" %></a></li>
                          <li><%= link_to "Tulsa", "/cities/1-tulsa" %></a></li>
                        </ul>
                        </div>
  
</center>

   <div class="container">
     <div class="col-xs-12">
       <div class="row">
         <% if @state.bills.where(['date >= ?', DateTime.now.to_date]).present? %>
         <b><%= link_to "upcoming votes", state_bills_path(@state) %></b><br>
         <% end %>  
        </div>
       
        <% @bills.order('date ASC').each do |bill| %>

        
        
<div class="row">
             
          
              <b><%= bill.date.strftime("%m/%d") %></b>: <div class="billtitle"><%= bill.title %> </div>
               </div> 
          <div class="row">
<div class="billdesc">
                    <%= auto_link(bill.description, :all, :target => "_blank").html_safe %>
                      </div>    
                    </div> 
                          
               
          

                          <div class="row">
                            <div class="trm">
<% if current_user && current_user.votes.where(:votable_id => bill.id, :up => true).present? %>
                            <b>Supported!</b>
                            <% else %>
                                </div>
                        <div class="sdf">
                            <b><%= link_to "Support", bill_votes_path(bill, :vote => {:up => true}), :remote => true, :method => :post, :class => "btn btn-xs btn-default" %></b>
                              <% end %>
                          </div>
                              <div class="sad">
                              (<b><%= bill.votes.where(:up => true).count %></b>)
                                </div>
                              <div class="tre">
                             <% if current_user && current_user.votes.where(:votable_id => bill.id, :up => false).present? %>
                            <b>Opposed!</b>
                                
                            <% else %>
                                </div>
                              <div class="sfd">
                            <b><%= link_to "Oppose", bill_votes_path(bill, :vote => {:up => false}), :remote => true, :method => :post, :class => "btn btn-xs btn-danger" %></b><% end %>
                                </div>
                              <div class="sado">
                                (<b><%= bill.votes.where(:up => false).count %></b>)
                            </div>

                       <%= link_to "Debate!", '#', class: 'btn btn-xs btn-primary reply-link', id: 'reply-link' %>
                          
                            <b><%= link_to "Link", [@state, bill], :class => "btn btn-xs btn-info" %></b>
                      <div class="linkpad">
                      </div>
                  <div class="reply-container", id='reply-container'>
                    <%= form_for([bill, Comment.new], :remote => true) do |f| %> 
                              <div class="field">
                                <%= f.text_area :message, class: "form-control", :placeholder =>"Comments must be at least 5 characters long..." %>
                              </div>
                              <div class="actions">
                                <%= f.submit :class => "btn btn-primary" %>
                              </div>
                                <% end %>
                            
                        
                         <%= render partial: "commentsL", locals: { bill: bill, comments: @comments } %> 
                  </div>
                      

        </div>  
          
        </div>

        <% end %>
     <br>
     <div class="row">
            <div id="filtersmob">
              <%= link_to "hot", state_path(@state, sort_by: "hot"), :class => "btn btn-xs btn-default" %>
                |
              <%= link_to "new", state_path(@state, sort_by: "new"), :class => "btn btn-xs btn-default" %>
              <div id="addlink">
                    <p>
                      <% if user_signed_in? %>
                      <%= link_to "Post", new_state_link_path(params[:id]), :class => "btn btn-xs btn-primary" %>
                      <% end %>
                    </p>
              </div>
            </div> 
        </div>
<div class="row">
  
    <% @links.each do |link| %> 
  <div class="linksmob">

      <div class="linkbody">
        <button type="button" class="btn btn-default"><b><%= link.score %></b></button>
        
    <%= link.title %>
                         
           <br>
<div class="linkdescm">
                    <%= auto_link(link.text, :all, :target => "_blank").html_safe %>
   </div>
                          <div id="linkauthmob">
                            posted <b><%= time_ago_in_words(link.created_at) %></b> ago<br>
                              by
                              <% if link.user.avatar? %><%= image_tag link.user.avatar.url(:main), :class => "img-rounded", :size => "25x25" %><% end %> 
                             <b><%= link.username %></b>
                          </div>
                 
                          
                        </div>
  
 <div class="row2mob"> 
   <div class="gup">
                               <% if current_user && current_user.votes.where(:votable_id => link.id, :up => true).present? %>
                          <div class="sdf">
                          <span class="glyphicon glyphicon-chevron-up"></span>
                            </div>
                            <% else %>
   
                          <div class="trigger">
                            <%= link_to link_votes_path(link, :vote => {:up => true}), :remote => true, :method => :post, class: "btn btn-small" do %>
                            
                            <span class="glyphicon glyphicon-chevron-up"></span>
                            
                          <% end %>
   </div>
 <% end %>
                            
                            <% if current_user && current_user.votes.where(:votable_id => link.id, :up => false).present? %>
                              <div class="sdfe">
                                  <span class="glyphicon glyphicon-chevron-down"></span>
     </div>                
                            <% else %>
                              
                          <div class="trigger-">
<%= link_to link_votes_path(link, :vote => {:up => false}), :method => :link, class: "btn btn-small" do %>
                            <span class="glyphicon glyphicon-chevron-down"></span>
                          <% end %>
                            </div>
                            <% end %>
                                
     <%= link_to "Debate!", '#', class: 'btn btn-xs btn-primary reply-link', id: 'reply-link' %>
     
                      <% if link.comments.count == 1 %>
                      (<b><%= link.comments.count %> </b> response)
                            <% else %>
                            (<b><%= link.comments.count %> </b> responses)
                            <% end %>
     <%= link_to "Link", [@state, link], class: 'btn btn-xs btn-info' %>
    
                      <div class="linkpad">
                      </div>
                  <div class="reply-container", id='reply-container'>
                                <%= form_for([link, Comment.new]) do |f| %> 
                              <div class="field">
                                <%= f.text_area :message, class: "form-control", :placeholder =>"Comments must be at least 5 characters long..." %>
                              </div>
                              <div class="actions">
                                <%= f.submit :class => "btn btn-primary" %>
                              </div>
                                <% end %>
                            
                        
                         <%= render partial: "comments", locals: { link: link, comments: @comments } %> 
                  </div>
       </div>

</div>

      </div>
  <% end %>

</div>

<%= will_paginate @links, renderer: BootstrapPagination::Rails %> 

</div>
</div>
</body>
</html>

app/views/states/show.html.erb
<head>
  <title>Democratize! <%= @state.title %> News, Politics, Discussion, Jobs, Events</title>

   <%= stylesheet_link_tag    "normal/application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <meta name="description" content="Democratize! <%= @state.title %> is a user-generated 'virtual town hall' for local news, politics, events, jobs, and debate.">
  <meta property="og:image" content='http://i59.tinypic.com/2e4ew5d.jpg'/>
</head>

<body>
<nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
 
<div class="padtop">
      <div class="logo">
        <%= link_to state_path do %>
        <i class="fa fa-bullhorn"></i> Democratize! <%= @state.title %> 
        <% end %>
    </div>  
    <div class="profnav">   
<% if current_user.present? %>
                <% if current_user.avatar? %>
                <%= image_tag current_user.avatar.url(:main), :class => "img-rounded", :size => "25x25" %>                
                <% end %>
                <b><%= current_user.username %></b>
        <div class="btn-group">
  
         
           <span class="caret dropdown-toggle" data-toggle="dropdown"></span>

    <ul class="dropdown-menu">
      <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
   
    </ul>
  </div>
        <% else %>
                <div class="altnav">
                  <%= link_to 'Sign In', new_user_session_path %> | 
                  <%= link_to 'Register!', new_user_registration_path %>
      </div>
                
                <% end %>



</div>
    </div>
    
  
</nav>
<div class="container">
    <div class="row">  
      <div class="col-xs-9">

        <div class="row">
            <div id="filters">
              <b><%= link_to "hot", state_path(@state, sort_by: "hot") %>
                |
                <%= link_to "new", state_path(@state, sort_by: "new") %></b>
              <div id="addlink">
                    <p>
                      <% if user_signed_in? %>
                     <%= link_to "Post", new_state_link_path(params[:id]), :class => "btn btn-xs btn-primary" %>
                    
                      <% end %>
                    </p>
              </div>
            </div> 
        </div>
        
          
          <div class="row">
            <% @links.each do |link| %> 
            <ul>                     
            <div id="links">
                <li>
                  <div class="row">
                    <div class="col-xs-1">
                      <div class="votes">
                        <div id="votesup">
                               <% if current_user.present? %>
       <% if current_user.id == 23 %>
                          <%= link_to link_votes_path(link, :vote => {:up => true}), :method => :link, class: "btn btn-small" do %>
                            
                       <span class="glyphicon glyphicon-chevron-up"></span>
                          <% end %>
                          <% end %>
                          <% end %>
                          <% if current_user && current_user.votes.where(:votable_id => link.id, :up => true).present? %>
                          <div id="glyphupP">
                          <span class="glyphicon glyphicon-chevron-up"></span>
                          </div>
                            <% else %>
                          <div class="trigger">
                          <%= link_to link_votes_path(link, :vote => {:up => true}), :remote => true, :method => :post, class: "btn btn-small" do %>
                        
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        
                          <% end %>
                            </div>
                          <% end %>
                        </div>
                         
                        <div id="votesS">
                          <%= link.score %> 
                        </div>
                         <div id="votesdown">
                            <% if current_user && current_user.votes.where(:votable_id => link.id, :up => false).present? %>
                                <div class="glyphdown">
                                  <span class="glyphicon glyphicon-chevron-down"></span>
                                </div>  
                            <% else %>
                          <div class="trigger-">
                            <%= link_to link_votes_path(link, :vote => {:up => false}), :remote => true, :method => :post, class: "btn btn-small" do %>
                         
                            <span class="glyphicon glyphicon-chevron-down"></span>
                            
                          <% end %>
                            </div>
                          <% end %>
                        </div>  
                      </div>
                    </div>  
                    <div class="col-xs-10">
                      <div class="row">
                        <div class="linkbody">
                            <%= link.title %></div> 
                        <div class="linkdesc">
                    <%= auto_link(link.text, :all, :target => "_blank").html_safe %>
                          
</div>       
                     
                                           
                      <div class="row">
                        <div class="col-xs-10">
                          <div id="linkauth">
                            posted <b><%= time_ago_in_words(link.created_at) %></b> ago
                              by
                            <% if link.user.avatar? %><%= image_tag link.user.avatar.url(:main), :class => "img-rounded", :size => "25x25" %><% end %> 
                             
                            <b><%= link.username %></b> <% if link.user.bio? %><em><%= link.user.bio %></em><% end %>                           
</div>
                        </div>
                      </div>
                      
                      
                        <div class="col-xs-10"> 
                          <div class="row">
                     
                       <%= link_to "Debate!", '#', class: 'btn btn-xs btn-primary reply-link', id: 'reply-link' %>
                          <% if link.comments.count == 1 %>
                      (<b><%= link.comments.count %> </b> response)
                            <% else %>
                            (<b><%= link.comments.count %> </b> responses)
                            <% end %>
                          
                            <b><%= link_to "Link", [@state, link] %></b>
                      <div class="linkpad">
                      </div>
                  <div class="reply-container", id='reply-container'>
                                <%= form_for([link, Comment.new], :remote => true) do |f| %> 
                              <div class="field">
                                <%= f.text_area :message, class: "form-control", :placeholder =>"Comments must be at least 5 characters long..." %>
                              </div>
                              <div class="actions">
                                <%= f.submit :class => "btn btn-primary" %>
                              </div>
                                <% end %>
                            
                        
                         <%= render partial: "comments", locals: { link: link, comments: @comments } %> 
                  </div>
                        </div>
                    </div> 
                    </div>
                      
                      
                 
                 
                </li>   
            </div>
            </ul> 
            <% end %> 
          </div>
          <div class="row">
            <div id="paginate">
            <%= will_paginate @links, renderer: BootstrapPagination::Rails %>
            </div>
            <br>
            <div id="footabout">
              
              <%= link_to "Contact", "mailto:democratizellc@gmail.com" %>
              </div>
            <div id="footabout">
            <%= link_to "Advertise!", "/pages/ads" %>
              </div>
             <div id="footabout">
            <%= link_to "Privacy", "/pages/privacy" %>
              </div>
            <div id="footabout">
            <%= link_to "Sitemap", "/pages/sitemap" %>
              </div>
            <div id="footcontact">
              <%= link_to "About", "/pages/show" %> 
              
            </div>
          </div>
        
</div>
          
       <div class="col-xs-3"> 

                  <% if @state.groups.present? %>
                   <ul class="nav nav-pills nav-stacked">
                      <br>  
                    
                      <li>
                        <h2><%= @state.title %> Groups</h2>
                    <% @groups.each do |group| %>
                        <%= link_to group.title, [@state, group], class: "list-group-item" %>
                      <% end %>
                   
                    
                      </li>
                    </ul>
                   
             
                  <% end %>
         <% if @state.resources.present? %>
                  <h2><%= @state.title %> News Sources</h2>
                      <% @resources.each do |resource| %>
                    <%= link_to resource.title, "http://#{resource.url}", target: '_blank' %>
                      <% end %>
                  <% end %>
                        
      </div>
<br>
        <div id="policy">

          <h2>Policy</h2>
          <p>All posts must be civil. Anything hateful, sexist, racist, abusive, threatening, etc. will be removed.</p>
        </div>
        
   
        <center>
                <div class="btn-group">
                        <button type="button" class="btn btn-success btn-sm dropdown-toggle" data-toggle="dropdown">
                          Change Location
                        <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><b><%= link_to "United States", "/" %></a></b></li>
                            <li class="divider"></li>
                          <li><b><%= link_to "Oklahoma", "/states/2-oklahoma" %></a></b></li>
                          <li><%= link_to "Oklahoma City", "/cities/2-oklahomacity" %></a></li>
                          <li><%= link_to "Tulsa", "/cities/1-tulsa" %></a></li>
                        </ul>
</div>
</center>
 </div>
        </div>
</div>

</body>