config/routes.rb
Sawit::Application.routes.draw do

  get "events/index"
  get "pages/ads"
  get "pages/privacy"
  get "pages/sitemap"
   devise_for :users
 

  resources :groups do
    member do
      get :follow
    end
  end

  resources :users do
    member do
      get :following
    end
  end

  resources :pages
  resources :users
  resources :ads

   resources :relationships, only: [:create, :destroy]
  

  resources :jobs do
    resources :comments
    resources :votes
  end

  resources :comments do
    resources :comments
    resources :votes
  end

  

  root :to => "countries#show", :id => '1'

  resources :states   do
    resources :links
    resources :groups do
    resources :links
  end
    resources :jobs 
    resources :resources
    resources :events
    resources :bills
  end

  resources :countries do
    resources :links
    resources :groups do
    resources :links
  end
    resources :jobs 
    resources :resources
    resources :events
    resources :bills
  end

  resources :reps do
    resources :links
  end

resources :districts do
  resources :links
end

resources :resources

resources :groups do
  resources :links
end

resources :cities do
  resources :links do
  resources :comments
  end
  resources :groups do
    resources :links
  end
  resources :jobs
  resources :districts do
    resources :links
  end 
  resources :resources
  resources :events
  resources :ads
  resources :bills
end

resources :links do
    resources :comments
    resources :votes
  end

  resources :events do
    resources :comments
    resources :votes
  end
  
    resources :bills do
    resources :comments
    resources :votes
  end

  

 

end

app/models/district.rb
class District < ActiveRecord::Base
	 OUR_EPOCH = Time.local(2005, 12, 8, 7, 46, 43).to_time
  has_many :links
  has_many :events
  has_many :jobs

	belongs_to :city
  belongs_to :state

def score
    ups = votes.where(:up => true).count
    downs = votes.where(:up => false).count
    ups - downs
  end
  

 def hot
  s = score
    displacement = Math.log( [s.abs, 1].max,  10 )
 
    sign = if s > 0
      1
    elsif s < 0
      -1
    else
      0
    end
 
    return (displacement * sign.to_f) + ( (created_at.to_i - OUR_EPOCH.to_i).to_f / 45000 )
  end 

end

app/controllers/districts_controller.rb
require 'will_paginate/array'
class DistrictsController < ApplicationController
  before_filter :find_parent, only: [:new, :create, :show]
  http_basic_authenticate_with name: "sammy1088", password: "Ce66$rio", except: [:show]
  def new
    @district = District.new
  end
  def create
  	@district = @parent.districts.new(district_params)
    respond_to do |format|
      if @district.save
        format.html { redirect_to @parent, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @district }
      else
        format.html { render action: 'new' }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end
  def index
    @districts = District.all
    @links = Link.all
  end
def show
  @district = District.find(params[:id])

  @city = City.find(params[:city_id])
  
  @groups = @city.groups  
  @districts = @city.districts
  @resources = @city.resources
  @jobs = @city.jobs
    
  @district = District.find(params[:id])
  @links = @district.links

  @cities = City.all


     if params[:sort_by] == "new"
      puts "sort queries called"
      @links = @links.order(created_at: :desc)
    else
    @links = @links.sort_by{ |l| l.hot }.reverse
    end
@links = @links.paginate(:page => params[:page], :per_page => 10)
    respond_to do |format|
    format.html               # /app/views/articles/index.html.erb
    format.html.tablet     # /app/views/posts/index.html+tablet.erb
    end
  end
  def edit
    @city = City.find(params[:city_id])
    @district = District.find(params[:id])
end
  def update
    @city = City.find(params[:city_id])
    @district = District.find(params[:id])
 
    if @district.update(params[:district].permit(:title))
      redirect_to [@city, @district]
  else
    render 'edit'
  end
end
  def destroy
    @district = District.find(params[:id])
    @district.destroy
  end
  private

   def district_params
    params.require(:district).permit(:title)
  end

  def find_parent
    if params[:city_id]
      @parent = City.find(params[:city_id])
  end
end
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/views/districts/_comments.html.erb
<% link.comments.sort_by{ |c| c.score }.reverse.each do |comment| %>

   <ul> 
     
     
<div class='message_group'>
   <div class="row">
      <%= link_to comment_votes_path(comment, :vote => {:comment_id => comment.id, :up => true}), :method => :comment, class: "btn btn-small" do %>
      <span class="glyphicon glyphicon-chevron-up"></span>
       <% end %>
       <%= comment.user.username %>
  <b><%= comment.score %></b> points 
          </div> 
     <div class="row">
       <%= link_to comment_votes_path(comment, :vote => {:comment_id => comment.id, :up => false}), :method => :comment, class: "btn btn-small" do %>
        <span class="glyphicon glyphicon-chevron-down"></span>
        <% end %>

       <b><%= auto_link(comment.message, :all, :target => "_blank").html_safe %></b>
      
                        
       </div>
    
                        <%= link_to "Reply", '#', class: 'reply-link', id: 'reply-link' %>
                  <div class="reply-container", id='reply-container'>
                  <%= form_for(Comment.new, url: comment_comments_path(comment)) do |f| %> 
              
                  <%= f.text_area :message, :class => "form-control", :placeholder =>"Add a comment" %>
                   
                      <%= f.submit :class => "btn btn-primary" %>
              
                  <% end %>
                                               
     </div>
                  
      
<div id="commentcomment">
<%= render partial: "commentscomments", locals: { comments: comment.comments } %>
</div>
</ul>

<% end %>

app/views/districts/edit.html.erb
edit

<%= form_for [@city, @district], :method => :patch do |f| %>

<p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

<p>
    <%= f.submit %>
  </p>
<% end %>

app/views/districts/index.html.erb
<% @districts.each do |district| %>
<%= link_to district.title %>
<%= button_to "delete", district, :method=>:delete, :class=>:destroy %>
<% end %>

app/views/districts/new.html.erb
<head>
  <title>Democratize! News, Politics, Discussion, Events</title>
  
   <%= stylesheet_link_tag    "normal/application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <meta name="description" content="Democratize! local news, politics, and community debate.">
  <meta property="og:image" content='http://i59.tinypic.com/2e4ew5d.jpg'/>
</head>
<%= form_for([@parent, @district]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/districts/show.html+tablet.erb
<!DOCTYPE html>
<html>
<head>
  <title>Democratize! <%= @city.title %> News, Politics, Discussion, Events</title>
  
   <%= stylesheet_link_tag    "mob/mob", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Democratize! <%= @city.title %> is a site for user-generated local news, politics, and opinion sharing in <%= @city.title %>.">
  <meta property="og:image" content='http://i59.tinypic.com/2e4ew5d.jpg'/>
</head>
<body>
<div class="bodymob">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
<div class="btn-group">
<button type="button" class="btn btn-default btn-lg navbar-btn navbar-left dropdown-toggle" data-toggle="dropdown">
    Menu <span class="caret"></span>
  </button>
  <ul class="dropdown-menu scrollable-menu" role="menu">
    <li><% if current_user.present? %>
                
                  <%= current_user.username %>
                  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>

                <% else %>
                
                  <li><%= link_to 'Sign In', new_user_session_path %></li>
                  <li><%= link_to 'Register Now!', new_user_registration_path %></li>
                
                <% end %></li>
    <li class="divider"></li>
    <li><%= @city.title %> Districts</li>
     <% @districts.each do |district| %>
    <li><%= link_to district.title, [@city, district] %></li>
    <% end %>   
    <li><%= @city.title %> Groups</li>
    <% @groups.each do |group| %>
    <li><%= link_to group.title, [@city, group] %></li>
    <% end %>
    <li><%= @city.title %> News Sources</li>
    <% @resources.each do |resource| %>
    <li><%= link_to resource.title, "http://#{resource.url}", target: '_blank' %></li>
    <% end %>
    
    <li class="divider"></li>
    <li><%= link_to "City Jobs", city_jobs_path(@city) %></li>
    <li><%= link_to "City Events", city_events_path(@city) %></li>
  </ul>
</div>


    <p class="navbar-text"><i class="fa fa-bullhorn"></i> <%= link_to "Democratize!", root_path %></p>

      
  </div>    
  </nav>
  
  
  <center>
    <div id="navtitle">
    <%= link_to @city.title, [@city] %> <%= @district.title %>
    </div>
  <div class="btn-group">
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                          Change Location
                        <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><b><%= link_to "United States", "/" %></a></b></li>
                            <li class="divider"></li>
                          <li><b><%= link_to "Oklahoma", "/states/2-oklahoma" %></a></b></li>
                          <li><%= link_to "Oklahoma City", "/cities/2-oklahomacity" %></a></li>
                          <li><%= link_to "Tulsa", "/cities/1-tulsa" %></a></li>
                        </ul>
                        </div>
  
</center>

   <div class="container">
     <div class="row">
            <div id="filtersmob">
                <%= link_to "hot", city_district_path(@city, @district, sort_by: "hot"), :class => "btn btn-xs btn-info" %>
                |
                <%= link_to "new", city_district_path(@city, @district, sort_by: "new"), :class => "btn btn-xs btn-info" %>
              <div id="addlink">
                    <p>
                      <% if user_signed_in? %>
                      <%= link_to "Post", new_district_link_path(params[:id]), :class => "btn btn-xs btn-primary" %>
                      <% end %>
                    </p>
              </div>
            </div> 
        </div>
<div class="row">
  
    <% @links.each do |link| %> 
  <div class="linksmob">

      <div class="linkbody">
        <button type="button" class="btn btn-default"><b><%= link.score %></b></button>
        
    <%= link.title %>
                         
                          <%= link_to "+", '#', class: 'btn btn-xs btn-success reply-link', id: 'reply-link' %>
                          
                  <div class="reply-container", id='reply-container'>
                    <%= auto_link(link.text, :all, :target => "_blank").html_safe %>
                          <div id="linkauthmob">
                            posted <b><%= time_ago_in_words(link.created_at) %></b> ago
                              by
                              <%= image_tag link.user.avatar.url(:main), :class => "img-rounded", :size => "25x25" %>
                              <b><%= link.username %></b> <% if link.user.bio? %><em>"<%= link.user.bio %>"</em><% end %>
                          </div>
                       </div>
                          
                        </div>
  
 <div class="row2mob"> 
   <div class="gup">
 <%= link_to link_votes_path(link, :vote => {:up => true}), :method => :link, class: "btn btn-small" do %>
                            <span class="glyphicon glyphicon-chevron-up"></span>
                          <% end %>
 
<%= link_to link_votes_path(link, :vote => {:up => false}), :method => :link, class: "btn btn-small" do %>
                            <span class="glyphicon glyphicon-chevron-down"></span>
                          <% end %>
     <%= link_to "Debate!", '#', class: 'btn btn-xs btn-primary reply-link', id: 'reply-link' %>
     
                      <% if link.comments.count == 1 %>
                      (<b><%= link.comments.count %> </b> response)
                            <% else %>
                            (<b><%= link.comments.count %> </b> responses)
                            <% end %>
                      <%= link_to "Link", [@parent, @district, link], class: 'btn btn-xs btn-info' %>
    
                      <div class="linkpad">
                      </div>
                  <div class="reply-container", id='reply-container'>
                                <%= form_for([link, Comment.new]) do |f| %> 
                              <div class="field">
                                <%= f.text_area :message, class: "form-control", :placeholder =>"Comments must be at least 5 characters long..." %>
                              </div>
                              <div class="actions">
                                <%= f.submit :class => "btn btn-primary" %>
                              </div>
                                <% end %>
                            
                        
                         <%= render partial: "comments", locals: { link: link, comments: @comments } %> 
                  </div>
       </div>

</div>

      </div>
  <% end %>

</div>

<%= will_paginate @links, renderer: BootstrapPagination::Rails %> 

</div>
</div>
</body>
</html>

app/views/districts/show.html.erb
<html>
<head>
  <title>Democratize! <%= @city.title %> News, Politics, Discussion, Events</title>
  
 <%= stylesheet_link_tag    "normal/application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <meta name="description" content="Democratize! <%= @city.title %> is a user generated hub for local news, politics, and opinion sharing in Tulsa, OK.">
  <meta property="og:image" content='http://i59.tinypic.com/2e4ew5d.jpg'/>
</head>
<body>
  <div class="bod">
    <div class="row">  
      <div class="col-xs-2">
        <div id="logo">
          <center><i class="fa fa-bullhorn"></i> <%= link_to "Democratize!", root_path %>
            <br><em><div id="tag">"a virtual town hall"</div></em></center>
        </div>
      </div>  
      <div class="col-xs-8">
        
        <div id="citytitle">
          <h1><%= link_to @city.title, [@city] %> <%= @district.title %></h1>
        </div>  
      </div>  
       <div class="col-xs-2"> 
            
      </div>
    </div>
    <div class="row">
      <div class="col-xs-2">
        <div id="sidebar">
              
              <div id="sideprof">
                <%# user is logged in, show log out link %>
             <br>  <% if current_user.present? %>

                <% if current_user.avatar? %>
                <%= image_tag current_user.avatar.url(:main), :class => "img-rounded", :size => "100x100" %>
                <br>
                <% end %>
                <b><%= current_user.username %></b><br>
                  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
                  
                  <%# user is not logged in, show signup and login links %>
                <% else %>
                
                  <li><%= link_to 'Sign In', new_user_session_path %></li>
                  <li><%= link_to 'Register Now!', new_user_registration_path %></li>
                
                <% end %>
                
               <%# if user_signed_in? %>

                <%# end %>
              </div>
                <div class="btn-group">
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                          Change Location
                        <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><b><%= link_to "United States", "/" %></a></b></li>
                            <li class="divider"></li>
                          <li><b><%= link_to "Oklahoma", "/states/2-oklahoma" %></a></b></li>
                          <li><%= link_to "Oklahoma City", "/cities/2-oklahomacity" %></a></li>
                          <li><%= link_to "Tulsa", "/cities/1-tulsa" %></a></li>
                        </ul>
                        </div>
                        
              <div id="sidenav">
                    
                <ul class="nav nav-pills nav-stacked">
                        
                      <br>
                      <li><center><b><%= @city.title %> Districts</b></center>
                        <% @districts.each do |district| %>
                      <%= link_to district.title, [@city, district], class: "list-group-item" %>
                       <% end %>
                    <br>
                    <center><b><%= @city.title %> Groups</b></center>
                    <% @groups.each do |group| %>
                    <%= link_to group.title, [@city, group], class: "list-group-item" %>
                      <% end %>
                      <br>
                      <center><b><%= @city.title %> News Sources</b></center>
                      <% @resources.each do |resource| %>
                    <%= link_to resource.title, "http://#{resource.url}", class: "list-group-item", target: '_blank' %>
                      <% end %>
                    
                      </li>
                    </ul>
              </div>
        </div>
      </div>
      <div class="col-xs-8">
        <div class="row">
            <div id="filters">
                <b><%= link_to "hot", city_district_path(@city, @district, sort_by: "hot") %>
                |
                  <%= link_to "new", city_district_path(@city, @district, sort_by: "new") %></b>
              <div id="addlink">
                    <p>
                      <% if user_signed_in? %>
                      <%= link_to "Post", new_district_link_path(params[:id]), :class => "btn btn-xs btn-primary" %>
                      <% end %>
                    </p>
              </div>
            </div> 
        </div>
        <div class="row">
          <div class="row">
            <% @links.each do |link| %> 
            <ul>                     
            <div id="links">
                <li>
                  <div class="row">
                    <div class="col-xs-1">
                      <div class="votes">
                        <div id="votesup">
                          <% if current_user && current_user.votes.where(:votable_id => link.id, :up => true).present? %>
                          <div class="glyphup">
                          <span class="glyphicon glyphicon-chevron-up"></span>
                          </div>
                            <% else %>
                          <%= link_to link_votes_path(link, :vote => {:up => true}), :method => :link, class: "btn btn-small" do %>
                            <span class="glyphicon glyphicon-chevron-up"></span>
                          <% end %>
                          <% end %>
                        </div>
                        <div id="votesS">
                          <%= link.score %> 
                        </div>
                        <div id="votesdown">  
                            <% if current_user && current_user.votes.where(:votable_id => link.id, :up => false).present? %>
                                <div class="glyphdown">
                                  <span class="glyphicon glyphicon-chevron-down"></span>
                                </div>  
                            <% else %>
                          <%= link_to link_votes_path(link, :vote => {:up => false}), :method => :link, class: "btn btn-small" do %>
                            <span class="glyphicon glyphicon-chevron-down"></span>
                          <% end %>
                          <% end %>
                        </div>  
                      </div>
                    </div>  
                    <div class="col-xs-10">
                      <div class="row">
                        <div class="linkbody">
                            <%= link.title %>
                         
                          <%= link_to "+read more", '#', class: 'btn btn-xs btn-default reply-link', id: 'reply-link' %>
                          
                  <div class="reply-container", id='reply-container'>
                    <%= auto_link(link.text, :all, :target => "_blank").html_safe %>
                          
                       </div>
                      </div> 
                      
                      <div class="row">
                        <div class="col-xs-10"> 
                          
                          <div id="linkauth">
                            posted <b><%= time_ago_in_words(link.created_at) %></b> ago
                              by
                              <%= image_tag link.user.avatar.url(:main), :class => "img-rounded", :size => "25x25" %>
                              <b><%= link.username %></b> <% if link.user.bio? %><em>"<%= link.user.bio %>"</em><% end %>
                          </div>
                        </div>
                       </div>
                        
                     
                      <div class="col-xs-10">
                    <div class="row">
                     
                       <%= link_to "Debate!", '#', class: 'btn btn-xs btn-primary reply-link', id: 'reply-link' %>
                      <% if link.comments.count == 1 %>
                      (<b><%= link.comments.count %> </b> response)
                            <% else %>
                            (<b><%= link.comments.count %> </b> responses)
                            <% end %>
                      <b><%= link_to "Link", [@parent, @district, link] %></b>
                      <div class="linkpad">
                      </div>
                  <div class="reply-container", id='reply-container'>
                                <%= form_for([link, Comment.new]) do |f| %> 
                              <div class="field">
                                <%= f.text_area :message, class: "form-control", :placeholder =>"Add a comment" %>
                              </div>
                              <div class="actions">
                                <%= f.submit :class => "btn btn-primary" %>
                              </div>
                                <% end %>
                            
                        
                         <%= render partial: "comments", locals: { link: link, comments: @comments } %> 
</div>
                        </div>
                    </div> 
                    </div>
                      
                      
                    </div>
                  </div>
                </li>   
            </div>
            </ul> 
            <% end %> 
          </div>
          <div class="row">
            <div id="paginate">
            <%= will_paginate @links %> 
            </div>
            <br>
            <div id="footabout">
              
              <%= link_to "Contact", "mailto:democratizellc@gmail.com" %>
              </div>
            <div id="footabout">
            <%= link_to "Advertise!", "/pages/ads" %>
              </div>
            <div id="footcontact">
              <%= link_to "About", "/pages/show" %> 
            </div>
          </div>
        </div>     
      </div> 

      <div class="col-xs-2"> 
        <div id="meetups">

      </div>
        <div id="policy">

     
        </div>
<div id="ads">

          </div>          
    </div>  
 
  
  
    </div>
  </div>   
</body>

</html>