config/routes.rb
Sawit::Application.routes.draw do

  get "events/index"
  get "pages/ads"
  get "pages/privacy"
  get "pages/sitemap"
   devise_for :users
 

  resources :groups do
    member do
      get :follow
    end
  end

  resources :users do
    member do
      get :following
    end
  end

  resources :pages
  resources :users
  resources :ads

   resources :relationships, only: [:create, :destroy]
  

  resources :jobs do
    resources :comments
    resources :votes
  end

  resources :comments do
    resources :comments
    resources :votes
  end

  

  root :to => "countries#show", :id => '1'

  resources :states   do
    resources :links
    resources :groups do
    resources :links
  end
    resources :jobs 
    resources :resources
    resources :events
    resources :bills
  end

  resources :countries do
    resources :links
    resources :groups do
    resources :links
  end
    resources :jobs 
    resources :resources
    resources :events
    resources :bills
  end

  resources :reps do
    resources :links
  end

resources :districts do
  resources :links
end

resources :resources

resources :groups do
  resources :links
end

resources :cities do
  resources :links do
  resources :comments
  end
  resources :groups do
    resources :links
  end
  resources :jobs
  resources :districts do
    resources :links
  end 
  resources :resources
  resources :events
  resources :ads
  resources :bills
end

resources :links do
    resources :comments
    resources :votes
  end

  resources :events do
    resources :comments
    resources :votes
  end
  
    resources :bills do
    resources :comments
    resources :votes
  end

  

 

end

app/models/city.rb
class City < ActiveRecord::Base
  OUR_EPOCH = Time.local(2005, 12, 8, 7, 46, 43).to_time
	has_many :links
	has_many :districts
  has_many :groups
  has_many :jobs
  has_many :resources
  has_many :events
  has_many :bills
  has_many :ads
  

	  def score
    ups = votes.where(:up => true).count
    downs = votes.where(:up => false).count
    ups - downs
  end
  

  def hot
  s = score
    displacement = Math.log( [s.abs, 1].max,  10 )
 
    sign = if s > 0
      1
    elsif s < 0
      -1
    else
      0
    end
 
    return (displacement * sign.to_f) + ( (created_at.to_i - OUR_EPOCH.to_i).to_f / 45000 )
  end 
	
end

app/controllers/cities_controller.rb
require 'will_paginate/array'
class CitiesController < ApplicationController
  before_filter :find_parent, only: [:new, :create]
  http_basic_authenticate_with name: "sammy1088", password: "Ce66$rio", except: [:show]
  
  def slug
    name.downcase.gsub(" ", "-")  
  end

  def to_param
    "#{id}-#{slug}"
  end

  
  def index
    @cities = City.all
    @links = Link.all

  end
  def new
    @city = City.new
    ##@link = @parent.links.new(link_params)
  end
  def create
   ##@link = @parent.links.new(link_params)
	 @city = City.new(city_params)
    @city.save
    redirect_to @city
  end
  def destroy
    @city = City.find(params[:id])
    @city.destroy
  end

  def show

    ##n@district = District.find(params[:id])
    @city = City.find(params[:id])
   
  
    @links = @city.links
    @districts = @city.districts
    @groups = @city.groups
    @resources = @city.resources
    @ads = @city.ads
    @bills = @city.bills.where(['date >= ?', DateTime.now.to_date]).limit(2)
    @jobs = @city.jobs.limit(5)
    @events = @city.events.where(['date >= ?', DateTime.now.to_date]).limit(5)
               
    
    
    if params[:sort_by] == "new"
      puts "sort queries called"
      
      @links = @links.order(created_at: :desc)

    else
    
    @links = @links.sort_by{ |l| l.hot }.reverse
    
    
    end

    @links = @links.paginate(:page => params[:page], :per_page => 15)
    
  respond_to do |format|
    format.html               # /app/views/articles/index.html.erb
    format.html.tablet     # /app/views/posts/index.html+tablet.erb
    end
  end
  private
   def city_params
    params.require(:city).permit(:title, :slug)
  end
  def find_parent
    if params[:city_id]
      @parent = City.find(params[:city_id])
  end
end
end

app/helpers/cities_helper.rb
module CitiesHelper
  def link_to_for_parent(parent)
    if parent.class == City
      link_to "Add a link", new_city_link_path(parent)
    end
  end
end

app/views/cities/_comments.html.erb
<% link.comments.sort_by{ |c| c.score }.reverse.each do |comment| %>

   <ul> 
     
     
<div class='message_group'>

   <div class="row">
     <% if current_user && current_user.votes.where(:votable_id => comment.id, :up => true).present? %>
                          <div class="ctriggerPL">
                          <span class="glyphicon glyphicon-chevron-up"></span>
                         </div>
                            <% else %>
     <div class="ctrigger">
     <%= link_to comment_votes_path(comment, :vote => {:up => true}), :remote => true, :method => :post, class: "btn btn-small" do %>
      <span class="glyphicon glyphicon-chevron-up"></span>
       <% end %>
       </div>
     <% end %>
     <b><%= comment.user.username %></b>
  <%= comment.score %> points 
          </div> 
     <div class="row">
       <% if current_user && current_user.votes.where(:votable_id => comment.id, :up => false).present? %>
                               <div class="ctriggerPLE">
                                  <span class="glyphicon glyphicon-chevron-down"></span>
                                </div>  
                            <% else %>
       <div class="ctrigger-">
       <%= link_to comment_votes_path(comment, :vote => {:up => false}), :remote => true, :method => :post, class: "btn btn-small" do %>
        <span class="glyphicon glyphicon-chevron-down"></span>
        <% end %>
         </div>
       <% end %>
       <%= auto_link(comment.message, :all, :target => "_blank").html_safe %>
      </div>
                        
     
    
                        <%= link_to "Reply", '#', class: 'reply-link', id: 'reply-link' %>
                  <div class="reply-container", id='reply-container'>
                  <%= form_for(Comment.new, url: comment_comments_path(comment), :remote => true) do |f| %> 
              
                  <%= f.text_area :message, :class => "form-control", :placeholder =>"Add a comment" %>
                    <div class="actions">
                      <%= f.submit :class => "btn btn-primary" %>
              </div>
                  <% end %>
                                               
     </div>
                  
      
<div id="commentcomment">
<%= render partial: "commentscomments", locals: { comments: comment.comments } %>
</div>
</ul>

<% end %>
       

app/views/cities/_commentsL.html.erb
<% bill.comments.sort_by{ |c| c.score }.reverse.each do |comment| %>

   <ul> 
     
     
<div class='message_group'>
   <div class="row">
          <% if current_user && current_user.votes.where(:votable_id => comment.id, :up => true).present? %>
                          <div class="ctriggerPL">
                          <span class="glyphicon glyphicon-chevron-up"></span>
                         </div>
                            <% else %>
     <div class="ctrigger">
      <%= link_to comment_votes_path(comment, :vote => {:up => true}), :remote => true, :method => :post, class: "btn btn-small" do %>
      <span class="glyphicon glyphicon-chevron-up"></span>
       <% end %>
       </div>
     <% end %>
       <%= comment.user.username %>
  <b><%= comment.score %></b> points 
          </div> 
     <div class="row">
       <% if current_user && current_user.votes.where(:votable_id => comment.id, :up => false).present? %>
                               <div class="ctriggerPLE">
                                  <span class="glyphicon glyphicon-chevron-down"></span>
                                </div>  
                            <% else %>
       <div class="ctrigger-">
       <%= link_to comment_votes_path(comment, :vote => {:up => false}), :remote => true, :method => :post, class: "btn btn-small" do %>
        <span class="glyphicon glyphicon-chevron-down"></span>
        <% end %>
         </div>
       <% end %>
       <b><%= auto_link(comment.message, :all, :target => "_blank").html_safe %></b>
      
                        
       </div>
    
                        <%= link_to "Reply", '#', class: 'reply-link', id: 'reply-link' %>
                  <div class="reply-container", id='reply-container'>
                    <%= form_for(Comment.new, url: comment_comments_path(comment), :remote => true) do |f| %> 
              
                  <%= f.text_area :message, :class => "form-control", :placeholder =>"Add a comment" %>
                   <div class="actions">
                      <%= f.submit :class => "btn btn-primary" %>
                 </div>              
                  <% end %>
                                               
     </div>
                  
      
<div id="commentcomment">
<%= render partial: "commentscommentsL", locals: { comments: comment.comments } %>
</div>
</ul>

<% end %>
     
     <div id="commpadB"></div>

app/views/cities/_commentscomments.html.erb
<% comments.sort_by{ |c| c.score }.reverse.each do |comment| %>

<ul> 
     
     
     <div class='message_group'>
<div class="row">
  <% if current_user && current_user.votes.where(:votable_id => comment.id, :up => true).present? %>
                          <div class="ctriggerPL">
                          <span class="glyphicon glyphicon-chevron-up"></span>
                         </div>
                            <% else %>
  <div class="ctrigger">
  <%= link_to comment_votes_path(comment, :vote => {:up => true}), :remote => true, :method => :post, class: "btn btn-small" do %>
                            <span class="glyphicon glyphicon-chevron-up"></i>
                          <% end %>
    </div>
  <% end %>
  <b><%= comment.user.username %></b>
  <%= comment.score %> points 
          </div> 
     <div class="row">
       <% if current_user && current_user.votes.where(:votable_id => comment.id, :up => false).present? %>
                               <div class="ctriggerPLE">
                                  <span class="glyphicon glyphicon-chevron-down"></span>
                                </div>  
                            <% else %>
       <div class="ctrigger-">
         <%= link_to comment_votes_path(comment, :vote => {:up => false}), :remote => true, :method => :post, class: "btn btn-small" do %>
                            <span class="glyphicon glyphicon-chevron-down"></i>
                          <% end %>
         </div>
<% end %>
       <%= auto_link(comment.message, :all, :target => "_blank").html_safe %>
      
                        
       </div>
    
                        <%= link_to "Reply", '#', class: 'reply-link', id: 'reply-link' %>
                  <div class="reply-container", id='reply-container'>
                  <%= form_for(Comment.new, url: comment_comments_path(comment), :remote => true) do |f| %> 
              
                  <%= f.text_area :message, :class => "form-control", :placeholder =>"Add a comment" %>
                     <div class="actions">
                      <%= f.submit :class => "btn btn-primary" %>
              </div>
                  <% end %>
                                               
     </div>
<div id="commentcomment">
<%= render partial: "commentscomments", locals: { comments: comment.comments } %>
</div>
</ul>

<% end %>
  <div id="commpad"></div>

app/views/cities/_commentscommentsL.html.erb
<% comments.sort_by{ |c| c.score }.reverse.each do |comment| %>

<ul> 
     
     
     <div class='message_group'>
<div class="row">
    <% if current_user && current_user.votes.where(:votable_id => comment.id, :up => true).present? %>
                          <div class="ctriggerPL">
                          <span class="glyphicon glyphicon-chevron-up"></span>
                         </div>
                            <% else %>
  <div class="ctrigger">
  <%= link_to comment_votes_path(comment, :vote => {:up => true}), :remote => true, :method => :post, class: "btn btn-small" do %>
  
                            <span class="glyphicon glyphicon-chevron-up"></i>
                          <% end %>
    </div>
  <% end %>
                       <%= comment.user.username %>
  <b><%= comment.score %></b> points 
          </div> 
     <div class="row">
              <% if current_user && current_user.votes.where(:votable_id => comment.id, :up => false).present? %>
                               <div class="ctriggerPLE">
                                  <span class="glyphicon glyphicon-chevron-down"></span>
                                </div>  
                            <% else %>
        <div class="ctrigger-">
       <%= link_to comment_votes_path(comment, :vote => {:up => false}), :remote => true, :method => :post, class: "btn btn-small" do %>
      
                            <span class="glyphicon glyphicon-chevron-down"></i>
                          <% end %>
         </div>
       <% end %>
       <b><%= auto_link(comment.message, :all, :target => "_blank").html_safe %></b>
      
                        
       </div>
    
                        <%= link_to "Reply", '#', class: 'reply-link', id: 'reply-link' %>
                  <div class="reply-container", id='reply-container'>
                    <%= form_for(Comment.new, url: comment_comments_path(comment), :remote => true) do |f| %> 
              
                  <%= f.text_area :message, :class => "form-control", :placeholder =>"Add a comment" %>
                   <div class="actions">
                      <%= f.submit :class => "btn btn-primary" %>
              </div>
                  <% end %>
                                               
     </div>
<div id="commentcomment">
<%= render partial: "commentscommentsL", locals: { comments: comment.comments } %>
</div>
</ul>

<% end %>

app/views/cities/index.html.erb
<% @cities.each do |city| %>
<%= link_to city.title %> <%= city.id %>
<%= button_to "delete", city, :method=>:delete, :class=>:destroy %>
<% end %>

app/views/cities/new.html.erb
<%= form_for :city, url: cities_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cities/show.html+tablet.erb
<!DOCTYPE html>

<head>
  <title>Democratize! <%= @city.title %> News, Politics, Discussion, Events</title>
  
   <%= stylesheet_link_tag    "mob/mob", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Democratize! <%= @city.title %> is a site for user-generated local news, politics, and opinion sharing in <%= @city.title %>.">
  <meta property="og:image" content='http://i59.tinypic.com/2e4ew5d.jpg'/>
</head>

<div class="bodymob">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
<div class="btn-group">
<button type="button" class="btn btn-default btn-lg navbar-btn navbar-left dropdown-toggle" data-toggle="dropdown">
    Menu <span class="caret"></span>
  </button>
  <ul class="dropdown-menu scrollable-menu" role="menu">
    <li><% if current_user.present? %>
                
                  <%= current_user.username %>
                  <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>

                <% else %>
                
                  <li><%= link_to 'Sign In', new_user_session_path %></li>
                  <li><%= link_to 'Register Now!', new_user_registration_path %></li>
                
                <% end %></li>
    <li class="divider"></li>
    <li><%= @city.title %> Districts</li>
     <% @districts.each do |district| %>
    <li><%= link_to district.title, [@city, district] %></li>
    <% end %>   
    <li><%= @city.title %> Groups</li>
    <% @groups.each do |group| %>
    <li><%= link_to group.title, [@city, group] %></li>
    <% end %>
    <li><%= @city.title %> News Sources</li>
    <% @resources.each do |resource| %>
    <li><%= link_to resource.title, "http://#{resource.url}", target: '_blank' %></li>
    <% end %>
    
    <li class="divider"></li>
    <li><%= link_to "City Jobs", city_jobs_path(@city) %></li>
    <li><%= link_to "City Events", city_events_path(@city) %></li>
  </ul>
</div>


    <p class="navbar-text"><i class="fa fa-bullhorn"></i> <%= link_to "Democratize!", root_path %></p>

      
  </div>    
  </nav>
  
  
  <center>
    <div id="navtitle">
    <%= @city.title %> News and Politics
    </div>
  <div class="btn-group">
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                          Change Location
                        <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><b><%= link_to "United States", "/" %></a></b></li>
                            <li class="divider"></li>
                          <li><b><%= link_to "Oklahoma", "/states/2-oklahoma" %></a></b></li>
                          <li><%= link_to "Oklahoma City", "/cities/2-oklahomacity" %></a></li>
                          <li><%= link_to "Tulsa", "/cities/1-tulsa" %></a></li>
                        </ul>
                        </div>
  
</center>

   <div class="container">
     <div class="col-xs-12">
       <div class="row">
          <% if @city.bills.where(['date >= ?', DateTime.now.to_date]).present? %>
          <b><%= link_to "upcoming votes", city_bills_path(@city) %></b><br>
         <% end %>  
        </div>
       
        <% @bills.order('date ASC').each do |bill| %>

        
        
<div class="row">
             
          
              <b><%= bill.date.strftime("%m/%d") %></b>: <div class="billtitle"><%= bill.title %> </div>
               </div> 
          <div class="row">
<div class="billdesc">
                    <%= auto_link(bill.description, :all, :target => "_blank").html_safe %>
                      </div>    
                    </div> 
                          
               
          

                          <div class="row">
                            <div class="trm">
<% if current_user && current_user.votes.where(:votable_id => bill.id, :up => true).present? %>
                            <b>Supported!</b>
                            <% else %>
                                </div>
                        <div class="sdf">
                            <b><%= link_to "Support", bill_votes_path(bill, :vote => {:up => true}), :remote => true, :method => :post, :class => "btn btn-xs btn-default" %></b>
                              <% end %>
                          </div>
                              <div class="sad">
                              (<b><%= bill.votes.where(:up => true).count %></b>)
                                </div>
                              <div class="tre">
                             <% if current_user && current_user.votes.where(:votable_id => bill.id, :up => false).present? %>
                            <b>Opposed!</b>
                                
                            <% else %>
                                </div>
                              <div class="sfd">
                            <b><%= link_to "Oppose", bill_votes_path(bill, :vote => {:up => false}), :remote => true, :method => :post, :class => "btn btn-xs btn-danger" %></b><% end %>
                                </div>
                              <div class="sado">
                                (<b><%= bill.votes.where(:up => false).count %></b>)
                            </div>

                       <%= link_to "Debate!", '#', class: 'btn btn-xs btn-primary reply-link', id: 'reply-link' %>
                          
                            <b><%= link_to "Link", [@city, bill], :class => "btn btn-xs btn-info" %></b>
                      <div class="linkpad">
                      </div>
                  <div class="reply-container", id='reply-container'>
                    <%= form_for([bill, Comment.new], :remote => true) do |f| %> 
                              <div class="field">
                                <%= f.text_area :message, class: "form-control", :placeholder =>"Comments must be at least 5 characters long..." %>
                              </div>
                              <div class="actions">
                                <%= f.submit :class => "btn btn-primary" %>
                              </div>
                                <% end %>
                            
                        
                         <%= render partial: "commentsL", locals: { bill: bill, comments: @comments } %> 
                  </div>
                      

        </div>  
          
        </div>

        <% end %>
     <br>
     <div class="row">
            <div id="filtersmob">
              <%= link_to "hot", city_path(@city, sort_by: "hot"), :class => "btn btn-xs btn-default" %>
                |
              <%= link_to "new", city_path(@city, sort_by: "new"), :class => "btn btn-xs btn-default" %>
              <div id="addlink">
                    <p>
                      <% if user_signed_in? %>
                      <%= link_to "Post", new_city_link_path(params[:id]), :class => "btn btn-xs btn-primary" %>
                      <% end %>
                    </p>
              </div>
            </div> 
        </div>
<div class="row">
  
    <% @links.each do |link| %> 
  <div class="linksmob">

      <div class="linkbody">
        <button type="button" class="btn btn-default"><b><%= link.score %></b></button>
        
    <%= link.title %>
                         
           <br>
<div class="linkdescm">
                    <%= auto_link(link.text, :all, :target => "_blank").html_safe %>
   </div>
                          <div id="linkauthmob">
                            posted <b><%= time_ago_in_words(link.created_at) %></b> ago<br>
                              by
                              <% if link.user.avatar? %><%= image_tag link.user.avatar.url(:main), :class => "img-rounded", :size => "25x25" %><% end %> 
                             <b><%= link.username %></b>
                          </div>
                 
                          
                        </div>
  
 <div class="row2mob"> 
   <div class="gup">
                               <% if current_user && current_user.votes.where(:votable_id => link.id, :up => true).present? %>
                          <div class="sdf">
                          <span class="glyphicon glyphicon-chevron-up"></span>
                            </div>
                            <% else %>
   
                          <div class="trigger">
                            <%= link_to link_votes_path(link, :vote => {:up => true}), :remote => true, :method => :post, class: "btn btn-small" do %>
                            
                            <span class="glyphicon glyphicon-chevron-up"></span>
                            
                          <% end %>
   </div>
 <% end %>
                            
                            <% if current_user && current_user.votes.where(:votable_id => link.id, :up => false).present? %>
                              <div class="sdfe">
                                  <span class="glyphicon glyphicon-chevron-down"></span>
     </div>                
                            <% else %>
                              
                          <div class="trigger-">
<%= link_to link_votes_path(link, :vote => {:up => false}), :method => :link, class: "btn btn-small" do %>
                            <span class="glyphicon glyphicon-chevron-down"></span>
                          <% end %>
                            </div>
                            <% end %>
                                
     <%= link_to "Debate!", '#', class: 'btn btn-xs btn-primary reply-link', id: 'reply-link' %>
     
                      <% if link.comments.count == 1 %>
                      (<b><%= link.comments.count %> </b> response)
                            <% else %>
                            (<b><%= link.comments.count %> </b> responses)
                            <% end %>
                      <%= link_to "Link", [@city, link], class: 'btn btn-xs btn-info' %>
    
                      <div class="linkpad">
                      </div>
                  <div class="reply-container", id='reply-container'>
                                <%= form_for([link, Comment.new]) do |f| %> 
                              <div class="field">
                                <%= f.text_area :message, class: "form-control", :placeholder =>"Comments must be at least 5 characters long..." %>
                              </div>
                              <div class="actions">
                                <%= f.submit :class => "btn btn-primary" %>
                              </div>
                                <% end %>
                            
                        
                         <%= render partial: "comments", locals: { link: link, comments: @comments } %> 
                  </div>
       </div>

</div>

      </div>
  <% end %>

</div>

<%= will_paginate @links, renderer: BootstrapPagination::Rails %> 

</div>
</div>
</body>
</html>